# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER=root
          POSTGRES_DB=recommendator_test
        user: root


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/recommendator-backend

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - recommendator-backend-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found


      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: recommendator-backend-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test

